[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "log2summary"
version = "0.1.0"
description = "CLI utility to summarize log levels in structured log files."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Gabe Chavez" }
]

[project.scripts]
log2summary = "log2summary.__main__:main"


[tool.setuptools]
packages = ["log2summary"]
